import subprocess
import logging
from ensemble_training import *

logging.basicConfig(level=logging.INFO)
log = logging.getLogger(__name__)
parent_dir = os.path.dirname(os.path.dirname(__file__))
out = subprocess.run(["./setup_spegg.sh"],cwd=parent_dir, capture_output=True, text=True)


def process_output(output : str, delimiter : str = "\t") -> list:
    """
    This will process the output potentially generated by sequencing software 
    and return a table where the first row is the header and the subsequent rows 
    are the data. The values will be converted to floats if possible, otherwise 
    they will be left as strings.

    :param output: The raw output string to process
    :type output: str
    :param delimiter: The delimiter used to separate values in the output
    :type delimiter: str
    """
    log.info("Processing output from sequencing software...")
    lines = output.strip().split("\n")
    data = []
    for line in lines:
        values = line.split(delimiter)
        data.append([float(v) if is_float(v) else v for v in values])
    return data

def generate_training_data(cfgs : dict, data : list) -> torch.Tensor:
    """
    After parsing the output from the sequencing software 
    into a list of lists (first one is header), this function 
    will generate the actual training data according to the configurations provided. 
    Usually this will pick a column and aggregate all the values in that column across 
    the rows to generate a training data point.
    Note that this function should be gradually worked on to fit specific needs.

    :param cfgs: A dictionary of configurations for how to generate the training data
    :type cfgs: dict
    :param data: The raw data parsed from the sequencing software output
    :type data: list
    """
    header = data[0]
    rows = data[1:]

    log.info("Generating training data from processed output...")

    col_idx_or_name = cfgs['column_name_or_idx']
    isindex = cfgs['column_index']

    training_col = [
        row[header.index(col_idx_or_name) if not isindex else col_idx_or_name] for row in rows
    ]

    point = np.mean(training_col)
    log.info(f"Generated training data point: {point}")

    return torch.tensor(np.full((cfgs['training_data_shape'][0], 
                    cfgs['training_data_shape'][1]), point, dtype=np.float32))