Data:
  delimiter: "\t"
  column_index: True
  column_name_or_idx: 5 
  training_data_shape: [2, 4]

Training:
  num_epochs: 100
  seed: 42
  batch_size: 4
  loss_function: 
    name: MSELoss
  learning_rate: 0.01
  to_learn:
    - M_reproductive_advantage
    - F_reproductive_advantage
    - TARGET_CROWN_COLOR
    - CROWN_COLOR_DECAY
    - phen_1_gene_phen_map_constant
    - phen_1_gene_phen_map_coef_0
    - phen_1_gene_phen_map_coef_1
    - phen_2_gene_phen_map_constant
    - phen_2_gene_phen_map_coef_0
    - phen_3_gene_phen_map_constant
    - phen_3_gene_phen_map_coef_0
    - loci_1_recombination_rates
    - loci_2_recombination_rates
    - loci_3_recombination_rates
    - loci_1_deme_mutation_rates
    - loci_2_deme_mutation_rates
    - loci_3_deme_mutation_rates
    - loci_1_deme_mutation_magnitudes
    - loci_2_deme_mutation_magnitudes
    - loci_3_deme_mutation_magnitudes
    # NOTE -- we need to have as many scaling factors as how many parameters 
    # we are simulating, and they need to be in the same order as the parameters 
    # in the name mapping above
  scaling_factors:
    M_reproductive_advantage: 1.0
    F_reproductive_advantage: 1.0
    TARGET_CROWN_COLOR: 1.0
    CROWN_COLOR_DECAY: 1.0
    phen_1_gene_phen_map_constant: 1.0
    phen_1_gene_phen_map_coef_0: 1.0
    phen_1_gene_phen_map_coef_1: 1.0
    phen_2_gene_phen_map_constant: 1.0
    phen_2_gene_phen_map_coef_0: 1.0
    phen_3_gene_phen_map_constant: 1.0
    phen_3_gene_phen_map_coef_0: 1.0
    loci_1_recombination_rates: 1.0
    loci_2_recombination_rates: 1.0
    loci_3_recombination_rates: 1.0
    loci_1_deme_mutation_rates: 1.0
    loci_2_deme_mutation_rates: 1.0
    loci_3_deme_mutation_rates: 1.0
    loci_1_deme_mutation_magnitudes: 1.0
    loci_2_deme_mutation_magnitudes: 1.0
    loci_3_deme_mutation_magnitudes: 1.0

  write_start: 0
  write_every: 1

NeuralNet:
  type: MLP
  .input_size: 8
  output_size: 20
  hidden_sizes: [64, 64]
  activation: ReLU
  optimizer: Adam
  num_threads: 1
  learning_rate: 1e-2
  loss_function: MSELoss
  device: cpu
  num_layers: 4
  nodes_per_layer: 
    default: ~
    layer_specific:
      0: 64
      1: 64
      2: 64
      3: 20
  activation_funcs:
    default: ReLU
  biases:
    default: ~
